spring:
  application:
    name: 'gateway'
  cloud:
    gateway:
      routes:
        - id: email-service
          uri: lb://email-service
          predicates:
            - Path= /email-service/**
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path= /posts/**, /media/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    configUrl: /v3/api-docs/swagger-config
    url: /v3/api-docs
    urls:
      - name: email-service
        url: /email-service/v3/api-docs
      - name: user-service
        url: /user-service/v3/api-docs
      - name: flight-service
        url: /flight-service/v3/api-docs
      - name: post-service
        url: /post-service/v3/api-docs